services:
  - type: web
    name: AI-HR-PROJECT
    env: python
    buildCommand: pip install -r requirements.txt && cd frontend && npm install && npm run build && cd .. && python manage.py collectstatic --noinput
    startCommand: gunicorn your_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: your_project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False