# Generated by Django 5.1.4 on 2024-12-06 11:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recruiter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("first_name", models.CharField(max_length=30, null=True)),
                ("last_name", models.CharField(max_length=30, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.TextField(null=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("image", models.BinaryField(null=True)),
                ("position", models.CharField(max_length=30, null=True)),
                ("responsible", models.CharField(max_length=128, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "password",
                    models.CharField(default="default_password", max_length=128),
                ),
                ("nb_candidates", models.IntegerField(default=0, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="recruiter_user_set", to="auth.group"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="recruiter_user_permissions",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "db_table": "recruiter",
                "ordering": ["-date_joined"],
            },
        ),
    ]
