# Generated by Django 5.1.3 on 2024-12-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Recruiter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruiter",
            name="first_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="recruiter",
            name="last_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="recruiter",
            name="position",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="recruiter",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("suspended", "Suspended"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
