# Generated by Django 5.1.3 on 2024-12-06 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("email", models.TextField(blank=True, null=True)),
                (
                    "added_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "resume_json_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "resume_json_updated_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "resume_file_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "resume_file_updated_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "resume_drive_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("job_title", models.CharField(blank=True, max_length=1000, null=True)),
                ("source", models.CharField(blank=True, max_length=100, null=True)),
                ("experience", models.IntegerField(null=True)),
                (
                    "availability",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("mobility", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.CharField(blank=True, max_length=15, null=True)),
                ("date_last_contacted", models.DateTimeField(null=True)),
                (
                    "contract_location",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "contract_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("salary_expectation", models.FloatField(blank=True, null=True)),
                ("previous_salary", models.FloatField(blank=True, null=True)),
                ("integration_date", models.DateField(null=True)),
                ("leave_balance", models.FloatField(blank=True, null=True)),
                ("date1", models.DateField(null=True)),
                (
                    "validated_by1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "evaluation1",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("date2", models.DateField(null=True)),
                (
                    "validated_by2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "evaluation2",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("date3", models.DateField(null=True)),
                (
                    "validated_by3",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "evaluation3",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
            ],
            options={
                "db_table": "candidate",
                "ordering": ["-added_at"],
            },
        ),
    ]
