# Generated by Django 5.1.3 on 2024-12-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Application", "0003_initial"),
        ("Candidate", "0001_initial"),
        ("Job", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="job",
            field=models.ManyToManyField(
                through="Application.Application", to="Job.job"
            ),
        ),
    ]
