# Generated by Django 5.1.3 on 2024-12-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Candidate", "0004_alter_candidate_contract_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="contract_location",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
