# Generated by Django 5.1.3 on 2024-12-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Candidate", "0008_alter_candidate_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="experience_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
