# Generated by Django 5.1.3 on 2024-12-18 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Candidate", "0009_candidate_experience_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="experience_description",
        ),
    ]
