# Generated by Django 5.1.3 on 2025-01-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Candidate", "0010_remove_candidate_experience_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="administrative_regularity",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="periode_preavis",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
