# Generated by Django 5.1.3 on 2025-01-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Candidate", "0011_candidate_administrative_regularity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
