# Generated by Django 5.1.3 on 2025-01-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Candidate", "0013_validationupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationupdate",
            name="administrative_regularity",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="validationupdate",
            name="contract_location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="validationupdate",
            name="contract_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="validationupdate",
            name="integration_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="validationupdate",
            name="periode_preavis",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="validationupdate",
            name="previous_salary",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="validationupdate",
            name="salary_expectation",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
