# Generated by Django 5.1.3 on 2025-01-14 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Candidate", "0014_validationupdate_administrative_regularity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HRUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "contract_location",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contract_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "salary_expectation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "previous_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("integration_date", models.DateField(blank=True, null=True)),
                (
                    "administrative_regularity",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "periode_preavis",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Candidate.candidate",
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
