# Generated by Django 5.1.3 on 2025-01-28 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Candidate", "0015_hrupdate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="stage",
            field=models.CharField(default="new", max_length=50),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="recruiter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_candidates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
