# Generated by Django 5.1.3 on 2024-12-06 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ("description", models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                "db_table": "activity",
                "ordering": ["-date"],
            },
        ),
    ]
