# Generated by Django 5.1.3 on 2024-12-06 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Activity", "0002_initial"),
        ("Client", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientfk",
                to="Client.client",
            ),
        ),
    ]
