# Generated by Django 5.1.3 on 2024-12-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Job", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="required_skills",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
