# Generated by Django 5.1.3 on 2024-12-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Job", "0003_job_required_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="competence_phare",
            field=models.CharField(
                blank=True,
                help_text="Core competency required for the job",
                max_length=255,
                null=True,
            ),
        ),
    ]
