# Generated by Django 5.1.3 on 2024-12-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Job", "0004_job_competence_phare"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_type_etiquette",
            field=models.CharField(
                blank=True,
                help_text="Job type classification (Technical/Functional/Technico-functional)",
                max_length=50,
                null=True,
            ),
        ),
    ]
