# Generated by Django 5.1.3 on 2024-12-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Job", "0005_job_job_type_etiquette"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="analysis_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="competences_autres",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="competences_complementaires",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="competences_metier_fondamentales",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="expertise_domaine_metier",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="outils_phares",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="repartition_responsabilites",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="responsabilites_principales",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="technologies_avancees",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="technologies_core",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="type_analyse_justification",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type_etiquette",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
