# Generated by Django 5.1.3 on 2024-12-24 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Job", "0006_job_analysis_date_job_competences_autres_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="competences_autres",
        ),
        migrations.RemoveField(
            model_name="job",
            name="competences_complementaires",
        ),
        migrations.RemoveField(
            model_name="job",
            name="competences_metier_fondamentales",
        ),
        migrations.RemoveField(
            model_name="job",
            name="expertise_domaine_metier",
        ),
        migrations.RemoveField(
            model_name="job",
            name="outils_phares",
        ),
        migrations.RemoveField(
            model_name="job",
            name="repartition_responsabilites",
        ),
        migrations.RemoveField(
            model_name="job",
            name="responsabilites_principales",
        ),
        migrations.RemoveField(
            model_name="job",
            name="technologies_avancees",
        ),
        migrations.RemoveField(
            model_name="job",
            name="technologies_core",
        ),
        migrations.RemoveField(
            model_name="job",
            name="type_analyse_justification",
        ),
    ]
