# Generated by Django 5.1.3 on 2025-02-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Job", "0007_remove_job_competences_autres_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="competences_autres",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="outils_phares",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="responsabilites_principales",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="technologies_core",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
