# Generated by Django 5.1.3 on 2025-02-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Job", "0008_job_competences_autres_job_outils_phares_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="deadline_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
