# Generated by Django 5.1.3 on 2025-02-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reminder", "0002_reminder_is_flagged_reminder_location_trigger_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reminder",
            name="is_flagged",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="location_trigger",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="notification_offset",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="notification_type",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="time_zone",
        ),
        migrations.RemoveField(
            model_name="reminderlist",
            name="smart_list_filter",
        ),
        migrations.AlterField(
            model_name="reminder",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="ReminderAttachment",
        ),
    ]
