# Generated by Django 5.1.3 on 2025-02-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reminder", "0003_remove_reminder_is_flagged_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="is_flagged",
            field=models.BooleanField(default=False),
        ),
    ]
