# Generated by Django 5.1.3 on 2025-01-29 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Job", "0007_remove_job_competences_autres_and_more"),
        ("Notification", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="job",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="Job.job"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(default="job_assignment", max_length=50),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
