# Generated by Django 5.1.3 on 2024-12-06 07:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=100, unique=True)),
                ("address", models.TextField(null=True)),
                ("image", models.BinaryField(null=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("website", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("industry", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prospect", "Prospect"),
                            ("partner", "Partner"),
                            ("lead", "Lead"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "engagement_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("talent outsourcing", "Talent Outsourcing"),
                            ("direct employment", "Direct Employment"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "headquarters_phone_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "urls",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "db_table": "client",
                "ordering": ["-added_at"],
            },
        ),
    ]
