# Generated by Django 5.1.3 on 2025-01-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Interview", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interview",
            name="recruiter",
        ),
        migrations.AddField(
            model_name="interview",
            name="interview_type",
            field=models.CharField(
                choices=[
                    ("recruiter", "Recruiter"),
                    ("partner", "Partner"),
                    ("client", "Client"),
                ],
                default="recruiter",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="interviewer_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
