# Generated by Django 5.1.3 on 2024-12-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("new", models.DateTimeField(null=True)),
                ("preselected", models.DateTimeField(null=True)),
                ("interviewed", models.DateTimeField(null=True)),
                ("tested", models.DateTimeField(null=True)),
                ("proposed", models.DateTimeField(null=True)),
                ("hired", models.DateTimeField(null=True)),
                ("start", models.DateTimeField(null=True)),
                ("end", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "application",
            },
        ),
    ]
