# Generated by Django 5.1.3 on 2025-01-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Lead", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
