# Generated by Django 5.1.3 on 2025-01-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Lead", "0003_lead_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="client_post",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
