# Generated by Django 5.1.3 on 2025-01-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Lead", "0004_lead_client_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lead",
            options={"ordering": ["-added_at"]},
        ),
    ]
